version: '3.8'

services:
  dev-environment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cfd26
    volumes:
      - .:/app
      - ./.vscode-server:/home/user/.vscode-server
    working_dir: /app
    environment:
      - TZ=Europe/Moscow
    tty: true
    stdin_open: true
    restart: unless-stopped
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
